# GitHub Metrics Workflow
# Reference: https://github.com/lowlighter/metrics#-documentation

name: GitHub Metrics

on:
  # Run every hour
  schedule:
    - cron: "0 * * * *"
    
  # Allow manual triggering
  workflow_dispatch:
  
  # Trigger on push to main or master
  push:
    branches: 
      - main
      - master

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to update repository content (e.g., README)

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # GitHub token with necessary scopes

          # Basic setup
          user: s3bu7i
          template: classic
          base: repositories
          config_timezone: Asia/Baku

          # Achievements plugin configuration
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 15
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: 100
